project:
  type: website
  output-dir: docs

website:
  title: "PNU 2023 Linear Algebra"
  sidebar:
    style: "docked"
    contents:
      - text: "Basics"
        contents:
          - 01_Linear_Systems.ipynb
          - 02_Gaussian_Elimination.ipynb
          - 03_Matrix_Algebra.ipynb
          - 04_Inverse_Matrices.ipynb
          - 05_LU_Factorization.ipynb
          - 06_Applications.ipynb
      - text: "Textbook Solutions"
        contents:
          - Textbook_Solutions.ipynb
      - text: "Appendix"
        contents:
          - A1_Numpy_Basic.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
