project:
  type: website
  output-dir: docs

website:
  title: "PNU 2023 Linear Algebra"
  sidebar:
    style: "docked"
    contents:
      - text: "Basics"
        contents:
          - Linear_Systems.ipynb
          - Gaussian_Elimination.ipynb
      - text: "Appendix"
        contents:
          - Numpy_Basic.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
