project:
  type: website
  output-dir: docs

website:
  title: "PNU 2023 Linear Algebra"
  sidebar:
    style: "docked"
    contents:
      - text: "Linear Systems"
        contents:
          - 01_Linear_Systems.ipynb
          - 02_Gaussian_Elimination.ipynb
          - 03_Matrix_Algebra.ipynb
          - 04_Inverse_Matrices.ipynb
          - 05_LU_Factorization.ipynb
          - 06_Applications_LS.ipynb
      - text: "Vector Spaces"
        contents:
          - 10_General_Linear_Systems.ipynb
          - 11_Linear_Combinations.ipynb
          - 12_Linear_Independence.ipynb
          - 13_Bases.ipynb
          - 14_Vector_Space_Examples.ipynb
          - 15_Applications_VS.ipynb
      - text: "Linear Transformations"
        contents:
          - 20_Matrix_Representations.ipynb
          - 21_Planar_Transformations.ipynb
          - 22_Applications_LT.ipynb
      - text: "Textbook Solutions"
        contents:
          - Textbook_Solutions.ipynb
      - text: "Appendix"
        contents:
          - A1_Numpy_Basic.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
